# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem "json", "~> 2.7.6"
gem "sinatra", "~> 2.0"

gem "rspec", "~> 3.9"

